CREATE TABLE taxes (
                       city VARCHAR(255) NOT NULL,
                       state VARCHAR(255) NOT NULL,
                       airportCode VARCHAR(255) NOT NULL,
                       surcharge integer NOT NULL,
                       PRIMARY KEY(airportCode)
);

INSERT INTO taxes (city, state, airportCode, surcharge) VALUES
( 'Bagotville', '  Que.', ' YBG ',  25 ),
( 'Baie-Comeau', '  Que.', ' YBC',  10 ),
( 'Bathurst', '  N.B.', ' ZBF',  40 ),
( 'Brandon', '  MB', ' YBR',  8.56 ),
( 'Calgary', '  Alta', ' YYC',  30 ),
( 'Castlegar', '  B.C.', ' YCG',  7 ),
( 'Charlo', '  N.B.', ' YCL',  40 ),
( 'Charlottetown', '  P.E.I.', ' YYG',  20 ),
( 'Comox', '  B.C.', ' YQQ',  5 ),
( 'Cranbrook', '  B.C.', ' YXC',  4 ),
( 'Deer Lake', '  N.L.', ' YDF',  20 ),
( 'Edmonton', '  Alta', ' YEG',  30 ),
( 'Flin Flon', '  MB', ' YFO',  30 ),
( 'Fort McMurray', '  Alta', ' YMM',  40 ),
( 'Fort St. John', '  B.C.', ' YXJ',  18 ),
( 'Fredericton', '  N.B.', ' YFC',  25 ),
( 'Gander', '  N.L.', ' YQX',  35 ),
( 'Gaspe', '  Que.', ' YGP',  15 ),
( 'Goose Bay', '  N.L.', ' YYR',  20 ),
( 'Grande Prairie', '  Alta', ' YQU',  25 ),
( 'Halifax', '  N.S.', ' YHZ',  28 ),
( 'Hamilton', '  Ont.', '  YHM',  25 ),
( 'Kamloops', '  B.C.', ' YKA',  10 ),
( 'Kapuskasing', '  Ont.', ' YYU',  11 ),
( 'Kelowna', '  B.C.', ' YLW',  20 ),
( 'Lethbridge', '  Alta', ' YQL',  20 ),
( 'London', '  Ont.', ' YXU',  7 ),
( 'Moncton', '  N.B.', ' YQM',  25 ),
( 'Mont-Joli', '  Que.', ' YYY',  13 ),
( 'Montréal', '  Que.', ' YUL',  30 ),
( 'Montréal', '  Que.', ' YMX',  13 ),
( 'Mont Tremblant', '  Que.', ' YTM',  25 ),
( 'Moosonee', '  Ont.', ' YMO',  12 ),
( 'Nanaimo', '  B.C.', ' YCD',  10 ),
( 'Ottawa', '  Ont.', ' YOW',  23 ),
( 'Prince Albert', '  Sask.', ' YPA',  17.50 ),
( 'Prince George', '  B.C.', ' YXS',  25 ),
( 'Prince Rupert', '  B.C.', ' YPR',  46 ),
( 'Quebec City', '  Que.', ' YQB',  35 ),
( 'Red Deer', '  Alta', ' YQF',  10 ),
( 'Regina', '  Sask.', ' YQR',  20 ),
( 'Rouyn-Noranda', '  Que.', ' YUY',  20 ),
( 'Saint John', '  N.B.', ' YSJ',  25 ),
( 'Sarnia', '  Ont.', ' YZR',  25 ),
( 'Saskatoon', '  Sask', ' YXE',  5 ),
( 'Sault Ste Marie', '  Ont.', ' YAM',  20 ),
( 'Smithers', '  B.C.', ' YYD',  30 ),
( 'Stephenville', '  N.L.', ' YJT',  25 ),
( 'St. John s', '  N.L.', ' YYT',  35 ),
( 'Sudbury', '  Ont.', ' YSB',  25 ),
( 'Sydney', '  N.S.', ' YQY',  25 ),
( 'Terrace', '  B.C.', ' YXT',  7 ),
( 'The Pas', '  Man.', ' YQD',  20 ),
( 'Thompson', '  Man.', ' YTH',  30 ),
( 'Timmins', '  Ont.', ' YTS',  10 ),
( 'Toronto', '  Ont.', ' YYZ',  25 ),
( 'Val d Or', '  Que.', ' YVO',  20 ),
( 'Vancouver', '  B.C.', ' YVR',  5 ),
( 'Victoria', '  B.C.', ' YYJ',  15 ),
( 'Waterloo', '  Ont.', ' YKF',  15 ),
( 'Windsor', '  Ont.', ' YQG',  15 ),
( 'Winnipeg', '  Man.', ' YWG',  25 ),
( 'Yellowknife', '  NWT', ' YZF',  20 );